project:
  type: website
  output-dir: site

website:
  title: "ROBOT FISICO"
  navbar:
    right:
    - href: index.qmd
      text: ğŸ  Inicio
    - href: about.qmd
      text: ğŸ“– Acerca de
    - href: histogramas/index.qmd
      text: ğŸ“Š Histogramas
    - href: contact.qmd
      text: âœ‰ï¸ Contact

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">


