project:
  type: website
  output-dir: site

website:
  title: "El FISICO ROBOT"
  navbar:
    right:
      - href: index.qmd
        text: ğŸ  Inicio
      - href: about.qmd
        text: ğŸ“– Acerca de
      - href: histogramas/index.qmd
        text: ğŸ“Š Histogramas
      - href: divulgacion.qmd
        text: ğŸ’¡DivulgaciÃ³n
      - href: contact.qmd
        text: âœ‰ï¸ Contacto

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">


