project:
  type: website
  output-dir: site

website:
  # TÃ­tulo del navbar con imagen y texto (se acepta HTML)
  title: "<span class='navbar-title'><img src='gato.png' alt='logo'>El FÃSICO ROBOT</span>"
  favicon: gato.png
  navbar:
    right:
      - href: index.qmd
        text: ğŸ  Inicio
      - href: about.qmd
        text: ğŸ“– Acerca de
      - href: histogramas/index.qmd
        text: ğŸ“Š Histogramas
      - href: divulgacion.qmd
        text: â“ Preguntas Frecuentes
      - href: contact.qmd
        text: âœ‰ï¸ Contacto

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <style>
            .navbar-title {
              display: flex;
              align-items: center;
            }
            .navbar-title img {
              height: 32px;
              margin-right: 10px;
            }
          </style>
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
